# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

julia:
  - 1.3.1

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

sudo: true

script:
  - sudo pip3 install xlrd
  - julia --version
  - julia --color=yes -e 'using Pkg; pkg"add ExcelReaders Millboard Jive"'
  - julia --color=yes -e 'using Pkg; pkg"add https://github.com/wookay/Lupin.jl.git"'
  - julia --color=yes --project=. ./games/nexonjojo/finder.jl
  - julia --color=yes --project=. -e 'using Pkg; Pkg.test()'

after_success:
  - if [[ "$TRAVIS_OS_NAME" == linux && "$TRAVIS_JULIA_VERSION" == 1.1 ]] ; then julia --project=. -e 'using Pkg;
                                                                                                       Pkg.add("Coverage");
                                                                                                       using Coverage;
                                                                                                       Codecov.submit(process_folder())' ; fi
