authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
name = "ThreeKingdoms"
uuid = "2eda8d22-0a9d-11e9-38c1-d96e883f27f6"
version = "0.1.0"

[compat]
julia = "1.2-DEV"

[deps]
ExcelReaders = "c04bee98-12a5-510c-87df-2a230cb6e075"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
