authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
name = "ThreeKingdoms"
uuid = "2eda8d22-0a9d-11e9-38c1-d96e883f27f6"
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[targets]
test = ["Test", "Jive"]
