module 人名錄 # ThreeKingdoms

const 丁儀 = (名 = "丁儀", 字 = "正禮", 이름 = "정의", 자 = "정례", Name = "Ding Yi")
const 丁原 = (名 = "丁原", 字 = "建陽", 이름 = "정원", 자 = "건양", Name = "Ding Yuan")
const 丁奉 = (名 = "丁奉", 이름 = "정봉", Name = "Ding Feng")
const 丁封 = (名 = "丁封", 이름 = "정봉", Name = "Ding Feng")
const 丁謐 = (名 = "丁謐", 字 = "彦靖", 이름 = "정밀", 자 = "언정", Name = "Ding Mi")
const 丘建 = (名 = "丘建", 이름 = "구건", Name = "Qiu Jian")
const 丘本 = (名 = "丘本", 이름 = "구본")
const 于吉 = (名 = "于吉", 이름 = "우길")
const 于禁 = (名 = "于禁", 字 = "文則", 이름 = "우금", 자 = "문칙", Name = "Yu Jin")
const 于詮 = (名 = "于詮", 이름 = "우전", Name = "Yu Quan")
const 令狐遇 = (名 = "令狐遇", 字 = "公治", 이름 = "영호우", 자 = "공치")
const 仲長統 = (名 = "仲長統", 字 = "公理", 이름 = "중장통", 자 = "공리", Name = "Zhongchang Tong")
const 伊籍 = (名 = "伊籍", 字 = "機伯", 이름 = "이적", 자 = "기백", Name = "Yi Ji")
const 伍延 = (名 = "伍延", 이름 = "오연", Name = "Wu Yan")
const 何儀 = (名 = "何儀", 이름 = "하의", Name = "He Yi")
const 何晏 = (名 = "何晏", 字 = "平叔", 이름 = "하안", 자 = "평숙", Name = "He Yan")
const 何植 = (名 = "何植", 이름 = "하식", Name = "He Zhi")
const 何進 = (名 = "何進", 字 = "遂高", 이름 = "하진", 자 = "수고", Name = "He Jin")
const 何顒 = (名 = "何顒", 字 = "伯求", 이름 = "하옹", 자 = "백구", Name = "He Yong")
const 來敏 = (名 = "來敏", 字 = "敬達", 이름 = "내민", 자 = "경달", Name = "Lai Min")
const 侯成 = (名 = "侯成", 이름 = "후성", Name = "Hou Cheng")
const 侯汶 = (名 = "侯汶", 字 = "文林", 이름 = "후문", 자 = "문림")
const 侯選 = (名 = "侯選", 이름 = "후선", Name = "Hou Xuan")
const 傅僉 = (名 = "傅僉", 이름 = "부첨", Name = "Fu Qian")
const 傅嘏 = (名 = "傅嘏", 字 = "蘭石", 이름 = "부하", 자 = "난석", Name = "Fu Jia")
const 傅士仁 = (名 = "傅士仁", 이름 = "부사인", Name = "Fu Shiren")
const 傅巽 = (名 = "傅巽", 字 = "公悌", 이름 = "부손", 자 = "공제", Name = "Fu Xun")
const 傅幹 = (名 = "傅幹", 字 = "彦材", 이름 = "부간", 자 = "언재", Name = "Fu Gan")
const 傅彤 = (名 = "傅彤", 이름 = "부동")
const 傅燮 = (名 = "傅燮", 字 = "南容", 이름 = "부섭", 자 = "남용", Name = "Fu Xie")
const 兀突骨 = (名 = "兀突骨", 이름 = "올돌골")
const 全尙 = (名 = "全尙", 字 = "子眞", 이름 = "전상", 자 = "자진")
const 全懌 = (名 = "全懌", 이름 = "전역", Name = "Quan Yi")
const 全琮 = (名 = "全琮", 字 = "子璜", 이름 = "전종", 자 = "자황", Name = "Quan Cong")
const 全禕 = (名 = "全禕", 이름 = "전위", Name = "Quan Yi")
const 全端 = (名 = "全端", 이름 = "전단", Name = "Quan Duan")
const 兪涉 = (名 = "兪涉", 이름 = "유섭")
const 公孫度 = (名 = "公孫度", 이름 = "공손도", Name = "Gongsun Du")
const 公孫康 = (名 = "公孫康", 이름 = "공손강", Name = "Gongsun Kang")
const 公孫恭 = (名 = "公孫恭", 이름 = "공손공", Name = "Gongsun Gong")
const 公孫淵 = (名 = "公孫淵", 字 = "文懿", 이름 = "공손연", 자 = "문의", Name = "Gongsun Yuan")
const 公孫瓚 = (名 = "公孫瓚", 字 = "伯圭", 이름 = "공손찬", 자 = "백규", Name = "Gongsun Zan")
const 公孫範 = (名 = "公孫範", 이름 = "공손범", Name = "Gongsun Fan")
const 公孫續 = (名 = "公孫續", 이름 = "공손속", Name = "Gongsun Xu")
const 公孫越 = (名 = "公孫越", 이름 = "공손월", Name = "Gongsun Yue")
const 典満 = (名 = "典満", 이름 = "전만")
const 典韋 = (名 = "典韋", 이름 = "전위", Name = "Dian Wei")
const 冷苞 = (名 = "冷苞", 이름 = "냉포")
const 劉丞 = (名 = "劉丞", 이름 = "유승", Name = "Liu Cheng")
const 劉備 = (名 = "劉備", 字 = "玄德", 이름 = "유비", 자 = "현덕", Name = "Liu Bei")
const 劉劭 = (名 = "劉劭", 字 = "孔才", 이름 = "유소", 자 = "공재", Name = "Liu Shao")
const 劉勳 = (名 = "劉勳", 이름 = "유훈", Name = "Liu Xun")
const 劉和 = (名 = "劉和", 이름 = "유화", Name = "Liu He")
const 劉囂 = (名 = "劉囂", 字 = "重寧", 이름 = "유오", 자 = "중녕", Name = "Liu Xiao")
const 劉封 = (名 = "劉封", 이름 = "유봉", Name = "Liu Feng")
const 劉岱 = (名 = "劉岱", 이름 = "유대", Name = "Liu Dai")
const 劉巴 = (名 = "劉巴", 字 = "子初", 이름 = "유파", 자 = "자초", Name = "Liu Ba")
const 劉度 = (名 = "劉度", 이름 = "유도", Name = "Liu Du")
const 劉廙 = (名 = "劉廙", 字 = "恭嗣", 이름 = "유이", 자 = "공사", Name = "Liu Yi")
const 劉循 = (名 = "劉循", 이름 = "유순", Name = "Liu Xun")
const 劉放 = (名 = "劉放", 字 = "子棄", 이름 = "유방", 자 = "자기", Name = "Liu Fang")
const 劉曄 = (名 = "劉曄", 字 = "子揚", 이름 = "유엽", 자 = "자양", Name = "Liu Ye")
const 劉楨 = (名 = "劉楨", 字 = "公幹", 이름 = "유정", 자 = "공간", Name = "Liu Zhen")
const 劉氏 = (名 = "劉氏", 이름 = "유씨", Name = "Lady Liu")
const 劉永 = (名 = "劉永", 字 = "公壽", 이름 = "유영", 자 = "공수", Name = "Liu Yong")
const 劉焉 = (名 = "劉焉", 字 = "君郞", 이름 = "유언", 자 = "군랑", Name = "Liu Yan")
const 劉理 = (名 = "劉理", 字 = "奉孝", 이름 = "유리", 자 = "봉효", Name = "Liu Li")
const 劉琦 = (名 = "劉琦", 이름 = "유기", Name = "Liu Qi")
const 劉琮 = (名 = "劉琮", 이름 = "유종", Name = "Liu Cong")
const 劉琰 = (名 = "劉琰", 字 = "威碩", 이름 = "유염", 자 = "위석", Name = "Liu Yan")
const 劉璋 = (名 = "劉璋", 字 = "季玉", 이름 = "유장", 자 = "계옥", Name = "Liu Zhang")
const 劉璝 = (名 = "劉璝", 이름 = "유괴", Name = "Liu Gui")
const 劉璿 = (名 = "劉璿", 이름 = "유선")
const 劉磐 = (名 = "劉磐", 이름 = "유반", Name = "Liu Pan")
const 劉禪 = (名 = "劉禪", 이름 = "유선", Name = "Liu Shan")
const 劉繇 = (名 = "劉繇", 이름 = "유요", Name = "Liu Yao")
const 劉虞 = (名 = "劉虞", 字 = "伯安", 이름 = "유우", 자 = "백안", Name = "Liu Yu")
const 劉表 = (名 = "劉表", 이름 = "유표", Name = "Liu Biao")
const 劉諶 = (名 = "劉諶", 이름 = "유심", Name = "Liu Chen")
const 劉賢 = (名 = "劉賢", 이름 = "유현", Name = "Liu Xian")
const 劉辟 = (名 = "劉辟", 이름 = "유벽", Name = "Liu Pi")
const 劉闡 = (Name = "Liu Chan", 名 = "劉闡", 이름 = "유천")
const 劉馥 = (名 = "劉馥", 字 = "元穎", 이름 = "유복", 자 = "원영", Name = "Liu Fu")
const 北斗 = (名 = "北斗", 이름 = "북두")
const 區星 = (名 = "區星", 이름 = "구성", Name = "Ou Xing")
const 卑衍 = (名 = "卑衍", 이름 = "비연", Name = "Bei Yan")
const 南斗 = (名 = "南斗", 이름 = "남두")
const 卞喜 = (名 = "卞喜", 이름 = "변희")
const 卞氏 = (名 = "卞氏", 이름 = "변씨", Name = "Lady Bian")
const 史渙 = (名 = "史渙", 字 = "公劉", 이름 = "사환", 자 = "공유", Name = "Shi Huan")
const 司馬伷 = (名 = "司馬伷", 字 = "子將", 이름 = "사마주", 자 = "자장", Name = "Sima Zhou")
const 司馬倫 = (名 = "司馬倫", 字 = "子彛", 이름 = "사마륜", 자 = "자이", Name = "Sima Lun")
const 司馬孚 = (名 = "司馬孚", 字 = "叔達", 이름 = "사마부", 자 = "숙달", Name = "Sima Fu")
const 司馬師 = (名 = "司馬師", 字 = "子元", 이름 = "사마사", 자 = "자원", Name = "Sima Shi")
const 司馬徽 = (名 = "司馬徽", 字 = "德操", 이름 = "사마휘", 자 = "덕조", Name = "Sima Hui")
const 司馬懿 = (名 = "司馬懿", 字 = "仲達", 이름 = "사마의", 자 = "중달", Name = "Sima Yi")
const 司馬攸 = (名 = "司馬攸", 字 = "大猷", 이름 = "사마유", 자 = "대유", Name = "Sima You")
const 司馬昭 = (名 = "司馬昭", 字 = "子上", 이름 = "사마소", 자 = "자상", Name = "Sima Zhao")
const 司馬朗 = (名 = "司馬朗", 字 = "伯達", 이름 = "사마랑", 자 = "백달", Name = "Sima Lang")
const 司馬望 = (名 = "司馬望", 字 = "子初", 이름 = "사마망", 자 = "자초", Name = "Sima Wang")
const 司馬炎 = (名 = "司馬炎", 字 = "安世", 이름 = "사마염", 자 = "안세", Name = "Sima Yan")
const 司馬駿 = (名 = "司馬駿", 字 = "子臧", 이름 = "사마준", 자 = "자장")
const 向寵 = (名 = "向寵", 이름 = "상총", Name = "Xiang Chong")
const 向朗 = (名 = "向朗", 이름 = "상랑", Name = "Xiang Lang")
const 吳國太 = (名 = "吳國太", 이름 = "오국태")
const 吳巨 = (名 = "吳巨", 이름 = "오거", Name = "Wu Ju")
const 吳懿 = (名 = "吳懿", 이름 = "오의", Name = "Wu Yi")
const 吳景 = (名 = "吳景", 이름 = "오경", Name = "Wu Jing")
const 吳班 = (名 = "吳班", 字 = "元雄", 이름 = "오반", 자 = "원웅", Name = "Wu Ban")
const 吳綱 = (名 = "吳綱", 이름 = "오강", Name = "Wu Gang")
const 吳蘭 = (名 = "吳蘭", 이름 = "오란", Name = "Wu Lan")
const 吳質 = (名 = "吳質", 字 = "季重", 이름 = "오질", 자 = "계중", Name = "Wu Zhi")
const 吾彦 = (名 = "吾彦", 字 = "士則", 이름 = "오언", 자 = "사칙")
const 吾粲 = (名 = "吾粲", 字 = "孔休", 이름 = "오찬", 자 = "공휴", Name = "Wu Can")
const 呂凱 = (名 = "呂凱", 字 = "季平", 이름 = "여개", 자 = "계평")
const 呂威璜 = (名 = "呂威璜", 이름 = "여위황")
const 呂岱 = (名 = "呂岱", 字 = "定公", 이름 = "여대", 자 = "정공")
const 呂布 = (名 = "呂布", 字 = "奉先", 이름 = "여포", 자 = "봉선", Name = "Lu Bu")
const 呂據 = (名 = "呂據", 字 = "世議", 이름 = "여거", 자 = "세의")
const 呂曠 = (名 = "呂曠", 이름 = "여광", Name = "Lu Kuang")
const 呂玲綺 = (名 = "呂玲綺", 이름 = "여령기")
const 呂範 = (名 = "呂範", 字 = "子衡", 이름 = "여범", 자 = "자형", Name = "Lu Fan")
const 呂翔 = (名 = "呂翔", 이름 = "여상", Name = "Lu Xiang")
const 呂蒙 = (名 = "呂蒙", 字 = "子明", 이름 = "여몽", 자 = "자명", Name = "Lu Meng")
const 呂虔 = (名 = "呂虔", 字 = "子恪", 이름 = "여건", 자 = "자각", Name = "Lu Qian")
const 周倉 = (名 = "周倉", 이름 = "주창", Name = "Zhou Cang")
const 周喁 = (名 = "周喁", 字 = "仁明", 이름 = "주우", 자 = "인명", Name = "Zhou Yu")
const 周旨 = (名 = "周旨", 이름 = "주지", Name = "Zhou Zhi")
const 周昂 = (名 = "周昂", 이름 = "주앙", Name = "Zhou Ang")
const 周昕 = (名 = "周昕", 字 = "大明", 이름 = "주흔", 자 = "대명", Name = "Zhou Xin")
const 周泰 = (名 = "周泰", 이름 = "주태", Name = "Zhou Tai")
const 周瑜 = (名 = "周瑜", 字 = "公瑾", 이름 = "주유", 자 = "공근", Name = "Zhou Yu")
const 周魴 = (名 = "周魴", 이름 = "주방", Name = "Zhou Fang")
const 和洽 = (名 = "和洽", 字 = "陽士", 이름 = "화흡", 자 = "양사", Name = "He Qia")
const 唐咨 = (名 = "唐咨", 이름 = "당자", Name = "Tang Zi")
const 唐彬 = (名 = "唐彬", 字 = "儒宗", 이름 = "당빈", 자 = "유종", Name = "Tang Bin")
const 嘉禾 = (名 = "嘉禾", 이름 = "가화")
const 嚴政 = (名 = "嚴政", 이름 = "엄정")
const 嚴畯 = (名 = "嚴畯", 字 = "曼才", 이름 = "엄준", 자 = "만재", Name = "Yan Jun")
const 嚴白虎 = (名 = "嚴白虎", 이름 = "엄백호", Name = "Yan Baihu")
const 嚴綱 = (名 = "嚴綱", 이름 = "엄강", Name = "Yan Gang")
const 嚴輿 = (名 = "嚴輿", 이름 = "엄여", Name = "Yan Yu")
const 嚴顔 = (名 = "嚴顔", 이름 = "엄안", Name = "Yan Yan")
const 國淵 = (名 = "國淵", 이름 = "국연", Name = "Guo Yuan")
const 士壹 = (名 = "士壹", 이름 = "사일", Name = "Sĩ Nhất")
const 士燮 = (名 = "士燮", 字 = "威彦", 이름 = "사섭", 자 = "위언", Name = "Sĩ Nhiếp")
const 夏侯令女 = (名 = "夏侯令女", 이름 = "하후영녀")
const 夏侯和 = (名 = "夏侯和", 字 = "義權", 이름 = "하후화", 자 = "의권", Name = "Xiahou He")
const 夏侯威 = (名 = "夏侯威", 字 = "季權", 이름 = "하후위", 자 = "계권", Name = "Xiahou Wei")
const 夏侯尙 = (名 = "夏侯尙", 字 = "伯仁", 이름 = "하후상", 자 = "백인", Name = "Xiahou Shang")
const 夏侯德 = (名 = "夏侯德", 이름 = "하후덕", Name = "Xiahou De")
const 夏侯恩 = (名 = "夏侯恩", 이름 = "하후은")
const 夏侯惇 = (名 = "夏侯惇", 字 = "元讓", 이름 = "하후돈", 자 = "원양", Name = "Xiahou Dun")
const 夏侯惠 = (名 = "夏侯惠", 字 = "稚權", 이름 = "하후혜", 자 = "치권", Name = "Xiahou Hui")
const 夏侯楙 = (名 = "夏侯楙", 字 = "子林", 이름 = "하후무", 자 = "자림", Name = "Xiahou Mao")
const 夏侯淵 = (名 = "夏侯淵", 字 = "妙才", 이름 = "하후연", 자 = "묘재", Name = "Xiahou Yuan")
const 夏侯玄 = (名 = "夏侯玄", 字 = "太初", 이름 = "하후현", 자 = "태초", Name = "Xiahou Xuan")
const 夏侯霸 = (名 = "夏侯霸", 字 = "仲權", 이름 = "하후패", 자 = "중권", Name = "Xiahou Ba")
const 夏候楙 = (名 = "夏候楙", 이름 = "하후무")
const 大喬 = (名 = "大喬", 이름 = "대교", Name = "Da Qiao")
const 太史享 = (名 = "太史享", 이름 = "태사향", Name = "Taishi Xiang")
const 太史慈 = (名 = "太史慈", 字 = "子義", 이름 = "태사자", 자 = "자의", Name = "Taishi Ci")
const 姜維 = (名 = "姜維", 字 = "伯約", 이름 = "강유", 자 = "백약", Name = "Jiang Wei")
const 婁圭 = (名 = "婁圭", 字 = "子伯", 이름 = "누규", 자 = "자백", Name = "Lou Gui")
const 孔伷 = (名 = "孔伷", 字 = "公緖", 이름 = "공주", 자 = "공서", Name = "Kong Zhou")
const 孔融 = (名 = "孔融", 字 = "文擧", 이름 = "공융", 자 = "문거", Name = "Kong Rong")
const 孟優 = (名 = "孟優", 이름 = "맹우", Name = "Meng You")
const 孟宗 = (名 = "孟宗", 이름 = "맹종")
const 孟獲 = (名 = "孟獲", 이름 = "맹획", Name = "Meng Huo")
const 孟達 = (名 = "孟達", 이름 = "맹달", Name = "Meng Da")
const 季雍 = (名 = "季雍", 이름 = "계옹", Name = "Ji Yong")
const 孫乾 = (名 = "孫乾", 字 = "公祐", 이름 = "손건", 자 = "공우", Name = "Sun Qian")
const 孫亮 = (名 = "孫亮", 字 = "子明", 이름 = "손량", 자 = "자명", Name = "Sun Liang")
const 孫仲 = (名 = "孫仲", 이름 = "손중")
const 孫休 = (名 = "孫休", 字 = "子烈", 이름 = "손휴", 자 = "자열", Name = "Sun Xiu")
const 孫冀 = (名 = "孫冀", 이름 = "손기")
const 孫匡 = (名 = "孫匡", 字 = "季佐", 이름 = "손광", 자 = "계좌", Name = "Sun Kuang")
const 孫和 = (名 = "孫和", 字 = "子孝", 이름 = "손화", 자 = "자효", Name = "Sun He")
const 孫堅 = (名 = "孫堅", 字 = "文臺", 이름 = "손견", 자 = "문대", Name = "Sun Jian")
const 孫尙香 = (名 = "孫尙香", 이름 = "손상향")
const 孫峻 = (名 = "孫峻", 字 = "子遠", 이름 = "손준", 자 = "자원", Name = "Sun Jun")
const 孫慮 = (名 = "孫慮", 字 = "子智", 이름 = "손려", 자 = "자지")
const 孫朗 = (名 = "孫朗", 字 = "早安", 이름 = "손랑", 자 = "조안", Name = "Sun Lang")
const 孫桓 = (名 = "孫桓", 이름 = "손환", Name = "Sun Huan")
const 孫權 = (名 = "孫權", 字 = "仲謀", 이름 = "손권", 자 = "중모", Name = "Sun Quan")
const 孫歆 = (名 = "孫歆", 이름 = "손흠")
const 孫氏 = (名 = "孫氏", 이름 = "손씨", Name = "Lady Sun")
const 孫瑜 = (名 = "孫瑜", 字 = "仲異", 이름 = "손유", 자 = "중이", Name = "Sun Yu")
const 孫異 = (名 = "孫異", 이름 = "손이", Name = "Sun Yi")
const 孫登 = (名 = "孫登", 字 = "子高", 이름 = "손등", 자 = "자고", Name = "Sun Deng")
const 孫皎 = (名 = "孫皎", 字 = "叔朗", 이름 = "손교", 자 = "숙랑", Name = "Sun Jiao")
const 孫皓 = (名 = "孫皓", 字 = "元宗", 이름 = "손호", 자 = "원종", Name = "Sun Hao")
const 孫禮 = (名 = "孫禮", 字 = "德達", 이름 = "손례", 자 = "덕달", Name = "Sun Li")
const 孫秀 = (名 = "孫秀", 이름 = "손수", Name = "Sun Xiu")
const 孫策 = (名 = "孫策", 字 = "伯符", 이름 = "손책", 자 = "백부", Name = "Sun Ce")
const 孫綝 = (名 = "孫綝", 字 = "子通", 이름 = "손침", 자 = "자통", Name = "Sun Chen")
const 孫羌 = (名 = "孫羌", 字 = "聖臺", 이름 = "손강", 자 = "성대")
const 孫翊 = (名 = "孫翊", 字 = "叔弼", 이름 = "손익", 자 = "숙필", Name = "Sun Yi")
const 孫覇 = (名 = "孫覇", 字 = "子威", 이름 = "손패", 자 = "자위")
const 孫觀 = (名 = "孫觀", 字 = "仲臺", 이름 = "손관", 자 = "중대", Name = "Sun Guan")
const 孫資 = (名 = "孫資", 字 = "彥龍", 이름 = "손자", 자 = "언룡", Name = "Sun Zi")
const 孫輔 = (名 = "孫輔", 字 = "國儀", 이름 = "손보", 자 = "국의", Name = "Sun Fu")
const 孫鄰 = (名 = "孫鄰", 字 = "公達", 이름 = "손린", 자 = "공달")
const 孫震 = (名 = "孫震", 이름 = "손진")
const 孫靜 = (名 = "孫靜", 字 = "幼臺", 이름 = "손정", 자 = "유대", Name = "Sun Jing")
const 孫韶 = (名 = "孫韶", 이름 = "손소", Name = "Sun Shao")
const 孫魯班 = (名 = "孫魯班", 이름 = "손노반", Name = "Sun Luban")
const 宋憲 = (名 = "宋憲", 이름 = "송헌", Name = "Song Xian")
const 宋謙 = (名 = "宋謙", 이름 = "송겸", Name = "Song Qian")
const 審榮 = (名 = "審榮", 이름 = "심영", Name = "Shen Rong")
const 審配 = (名 = "審配", 字 = "正南", 이름 = "심배", 자 = "정남", Name = "Shen Pei")
const 射援 = (名 = "射援", 字 = "文雄", 이름 = "사원", 자 = "문웅", Name = "She Yuan")
const 小喬 = (名 = "小喬", 이름 = "소교", Name = "Xiao Qiao")
const 少帝 = (名 = "少帝", 이름 = "소제")
const 尹大目 = (名 = "尹大目", 이름 = "윤대목", Name = "Yin Damu")
const 尹奉 = (名 = "尹奉", 字 = "次曾", 이름 = "윤봉", 자 = "차증", Name = "Yin Feng")
const 尹賞 = (名 = "尹賞", 이름 = "윤상", Name = "Yin Shang")
const 尹默 = (名 = "尹默", 字 = "思潛", 이름 = "윤묵", 자 = "사잠", Name = "Yin Mo")
const 岑昏 = (名 = "岑昏", 이름 = "잠혼", Name = "Cen Hun")
const 崔林 = (名 = "崔林", 字 = "德儒", 이름 = "최림", 자 = "덕유", Name = "Cui Lin")
const 崔琰 = (名 = "崔琰", 字 = "季珪", 이름 = "최염", 자 = "계규", Name = "Cui Yan")
const 州泰 = (名 = "州泰", 이름 = "주태", Name = "Zhou Tai")
const 左奕 = (名 = "左奕", 이름 = "좌혁", Name = "Zuo Yi")
const 左慈 = (名 = "左慈", 字 = "元放", 이름 = "좌자", 자 = "원방", Name = "Zuo Ci")
const 師纂 = (名 = "師纂", 이름 = "사찬", Name = "Shi Zuan")
const 帶來洞主 = (名 = "帶來洞主", 이름 = "대래동주")
const 常林 = (名 = "常林", 字 = "伯槐", 이름 = "상림", 자 = "백괴", Name = "Chang Lin")
const 廖化 = (名 = "廖化", 字 = "元儉", 이름 = "요화", 자 = "원검", Name = "Liao Hua")
const 廖立 = (名 = "廖立", 字 = "公淵", 이름 = "요립", 자 = "공연", Name = "Liao Li")
const 张梁 = (名 = "张梁", 이름 = "장량")
const 張任 = (名 = "張任", 이름 = "장임", Name = "Zhang Ren")
const 張休 = (名 = "張休", 字 = "叔嗣", 이름 = "장휴", 자 = "숙사", Name = "Zhang Xiu")
const 張儉 = (名 = "張儉", 字 = "元節", 이름 = "장검", 자 = "원절", Name = "Zhang Jian")
const 張允 = (名 = "張允", 이름 = "장윤", Name = "Zhang Yun")
const 張勳 = (名 = "張勳", 이름 = "장훈")
const 張南 = (名 = "張南", 이름 = "장남", Name = "Zhang Nan")
const 張寶 = (名 = "張寶", 이름 = "장보", Name = "Zhang Bao")
const 張嶷 = (名 = "張嶷", 이름 = "장억")
const 張布 = (名 = "張布", 이름 = "장포", Name = "Zhang Bu")
const 張恂 = (名 = "張恂", 이름 = "장순", Name = "Zhang Xun")
const 張悌 = (名 = "張悌", 이름 = "장제", Name = "Zhang Ti")
const 張承 = (名 = "張承", 字 = "仲嗣", 이름 = "장승", 자 = "중사", Name = "Zhang Cheng")
const 張旣 = (名 = "張旣", 이름 = "장기")
const 張春華 = (名 = "張春華", 이름 = "장춘화", Name = "Zhang Chunhua")
const 張昭 = (名 = "張昭", 이름 = "장소", Name = "Zhang Zhao")
const 張曼成 = (名 = "張曼成", 이름 = "장만성", Name = "Zhang Mancheng")
const 張松 = (名 = "張松", 이름 = "장송", Name = "Zhang Song")
const 張楊 = (名 = "張楊", 이름 = "장양", Name = "Zhang Yang")
const 張橫 = (名 = "張橫", 이름 = "장횡", Name = "Zhang Heng")
const 張溫 = (名 = "張溫", 이름 = "장온", Name = "Zhang Wen")
const 張濟 = (名 = "張濟", 이름 = "장제", Name = "Zhang Ji")
const 張燕 = (名 = "張燕", 이름 = "장연", Name = "Zhang Yan")
const 張特 = (名 = "張特", 字 = "子産", 이름 = "장특", 자 = "자산", Name = "Zhang Te")
const 張球 = (名 = "張球", 이름 = "장구")
const 張範 = (名 = "張範", 字 = "公儀", 이름 = "장범", 자 = "공의", Name = "Zhang Fan")
const 張紘 = (名 = "張紘", 字 = "子綱", 이름 = "장굉", 자 = "자강", Name = "Zhang Hong")
const 張紹 = (名 = "張紹", 이름 = "장소", Name = "Zhang Shao")
const 張緝 = (名 = "張緝", 이름 = "장집")
const 張繡 = (名 = "張繡", 이름 = "장수", Name = "Zhang Xiu")
const 張翼 = (名 = "張翼", 字 = "伯恭", 이름 = "장익", 자 = "백공", Name = "Zhang Yi")
const 張苞 = (名 = "張苞", 이름 = "장포", Name = "Zhang Bao")
const 張英 = (名 = "張英", 이름 = "장영", Name = "Zhang Ying")
const 張華 = (名 = "張華", 字 = "茂先", 이름 = "장화", 자 = "무선", Name = "Zhang Hua")
const 張虎 = (名 = "張虎", 이름 = "장호", Name = "Zhang Hu")
const 張衛 = (名 = "張衛", 字 = "公則", 이름 = "장위", 자 = "공칙", Name = "Zhang Wei")
const 張裔 = (名 = "張裔", 字 = "君嗣", 이름 = "장예", 자 = "군사", Name = "Zhang Yi")
const 張角 = (名 = "張角", 이름 = "장각", Name = "Zhang Jue")
const 張遵 = (名 = "張遵", 이름 = "장준", Name = "Zhang Zun")
const 張遼 = (名 = "張遼", 字 = "文遠", 이름 = "장료", 자 = "문원", Name = "Zhang Liao")
const 張邈 = (名 = "張邈", 字 = "孟卓", 이름 = "장막", 자 = "맹탁", Name = "Zhang Miao")
const 張郃 = (名 = "張郃", 字 = "儁乂", 이름 = "장합", 자 = "준예", Name = "Zhang He")
const 張闓 = (名 = "張闓", 이름 = "장개", Name = "Zhang Kai")
const 張飛 = (名 = "張飛", 이름 = "장비", Name = "Zhang Fei")
const 張魯 = (名 = "張魯", 이름 = "장로", Name = "Zhang Lu")
const 彭羕 = (名 = "彭羕", 字 = "永年", 이름 = "팽양", 자 = "영년", Name = "Peng Yang")
const 徐庶 = (名 = "徐庶", 이름 = "서서", Name = "Xu Shu")
const 徐晃 = (名 = "徐晃", 字 = "公明", 이름 = "서황", 자 = "공명", Name = "Xu Huang")
const 徐榮 = (名 = "徐榮", 이름 = "서영", Name = "Xu Rong")
const 徐氏 = (名 = "徐氏", 이름 = "서씨", Name = "Lady Xu")
const 徐盛 = (名 = "徐盛", 字 = "文響", 이름 = "서성", 자 = "문향", Name = "Xu Sheng")
const 徐質 = (名 = "徐質", 이름 = "서질", Name = "Xu Zhi")
const 徐邈 = (名 = "徐邈", 字 = "景山", 이름 = "서막", 자 = "경산", Name = "Xu Miao")
const 忙牙長 = (名 = "忙牙長", 이름 = "망아장")
const 應劭 = (名 = "應劭", 字 = "仲瑗", 이름 = "응소", 자 = "중원", Name = "Ying Shao")
const 應瑒 = (名 = "應瑒", 字 = "德璉", 이름 = "응창", 자 = "덕련", Name = "Ying Yang")
const 應貞 = (名 = "應貞", 字 = "吉甫", 이름 = "응정", 자 = "길보", Name = "Ying Zhen")
const 成公英 = (名 = "成公英", 이름 = "성공영", Name = "Chenggong Ying")
const 成宜 = (名 = "成宜", 이름 = "성의", Name = "Cheng Yi")
const 戲志才 = (名 = "戲志才", 이름 = "희지재", Name = "Xi Zhicai")
const 戴陵 = (名 = "戴陵", 이름 = "대릉", Name = "Dai Ling")
const 文欽 = (名 = "文欽", 字 = "仲若", 이름 = "문흠", 자 = "중약", Name = "Wen Qin")
const 文聘 = (名 = "文聘", 字 = "仲業", 이름 = "문빙", 자 = "중업", Name = "Wen Ping")
const 文虎 = (名 = "文虎", 이름 = "문호", Name = "Wen Hu")
const 文醜 = (名 = "文醜", 이름 = "문추", Name = "Wen Chou")
const 文鴦 = (名 = "文鴦", 이름 = "문앙", Name = "Wen Yang")
const 方悅 = (名 = "方悅", 이름 = "방열")
const 施朔 = (名 = "施朔", 이름 = "시삭", Name = "Shi Shuo")
const 曁艶 = (名 = "曁艶", 字 = "子休", 이름 = "글염", 자 = "자휴")
const 曹丕 = (名 = "曹丕", 字 = "子桓", 이름 = "조비", 자 = "자환", Name = "Cao Pi")
const 曹仁 = (名 = "曹仁", 字 = "子孝", 이름 = "조인", 자 = "자효", Name = "Cao Ren")
const 曹休 = (名 = "曹休", 字 = "文烈", 이름 = "조휴", 자 = "문렬", Name = "Cao Xiu")
const 曹冏 = (名 = "曹冏", 字 = "元首", 이름 = "조경", 자 = "원수", Name = "Cao Jiong")
const 曹叡 = (名 = "曹叡", 字 = "元仲", 이름 = "조예", 자 = "원중", Name = "Cao Rui")
const 曹奐 = (名 = "曹奐", 이름 = "조환", Name = "Cao Huan")
const 曹宇 = (名 = "曹宇", 字 = "彭祖", 이름 = "조우", 자 = "팽조", Name = "Cao Yu")
const 曹嵩 = (名 = "曹嵩", 字 = "巨高", 이름 = "조숭", 자 = "거고", Name = "Cao Song")
const 曹彰 = (名 = "曹彰", 字 = "子文", 이름 = "조창", 자 = "자문", Name = "Cao Zhang")
const 曹性 = (名 = "曹性", 이름 = "조성", Name = "Cao Xing")
const 曹操 = (名 = "曹操", 이름 = "조조", Name = "Cao Cao")
const 曹昻 = (Name = "Cao Ang", 名 = "曹昻", 이름 = "조앙")
const 曹昂 = 曹昻
const 曹植 = (名 = "曹植", 字 = "子建", 이름 = "조식", 자 = "자건", Name = "Cao Zhi")
const 曹沖 = (名 = "曹沖", 이름 = "조충", Name = "Cao Chong")
const 曹洪 = (名 = "曹洪", 이름 = "조홍", Name = "Cao Hong")
const 曹熊 = (名 = "曹熊", 이름 = "조웅", Name = "Cao Xiong")
const 曹爽 = (名 = "曹爽", 이름 = "조상", Name = "Cao Shuang")
const 曹珍 = (Name = "Cao Zhen", 名 = "曹珍", 이름 = "조진")
const 曹眞 = (名 = "曹眞", 字 = "子丹", 이름 = "조진", 자 = "자단", Name = "Cao Zhen")
const 曹純 = (名 = "曹純", 이름 = "조순", Name = "Cao Chun")
const 曹纂 = (名 = "曹纂", 字 = "德思", 이름 = "조찬", 자 = "덕사", Name = "Cao Zuan")
const 曹羲 = (名 = "曹羲", 이름 = "조희", Name = "Cao Xi")
const 曹芳 = (名 = "曹芳", 字 = "蘭卿", 이름 = "조방", 자 = "난경", Name = "Cao Fang")
const 曹訓 = (名 = "曹訓", 이름 = "조훈", Name = "Cao Xun")
const 曹豹 = (名 = "曹豹", 이름 = "조표", Name = "Cao Bao")
const 曹騰 = (名 = "曹騰", 字 = "季興", 이름 = "조등", 자 = "계흥", Name = "Cao Teng")
const 曹髦 = (名 = "曹髦", 字 = "彦士", 이름 = "조모", 자 = "언사", Name = "Cao Mao")
const 木鹿大王 = (名 = "木鹿大王", 이름 = "목록대왕")
const 朱儁 = (名 = "朱儁", 이름 = "주준", Name = "Zhu Jun")
const 朱才 = (名 = "朱才", 字 = "君業", 이름 = "주재", 자 = "군업", Name = "Zhu Cai")
const 朱據 = (名 = "朱據", 字 = "子範", 이름 = "주거", 자 = "자범")
const 朱桓 = (名 = "朱桓", 이름 = "주환", Name = "Zhu Huan")
const 朱治 = (名 = "朱治", 字 = "君理", 이름 = "주치", 자 = "군리", Name = "Zhu Zhi")
const 朱然 = (名 = "朱然", 이름 = "주연", Name = "Zhu Ran")
const 朱異 = (名 = "朱異", 字 = "季文", 이름 = "주이", 자 = "계문", Name = "Zhu Yi")
const 朱褒 = (名 = "朱褒", 이름 = "주포", Name = "Zhu Bao")
const 朱靈 = (名 = "朱靈", 字 = "文博", 이름 = "주령", 자 = "문박", Name = "Zhu Ling")
const 朶思大王 = (名 = "朶思大王", 이름 = "타사대왕")
const 李傕 = (名 = "李傕", 字 = "稚然", 이름 = "이각", 자 = "치연", Name = "Li Jue")
const 李儒 = (名 = "李儒", 字 = "文優", 이름 = "이유", 자 = "문우", Name = "Li Ru")
const 李典 = (名 = "李典", 字 = "曼成", 이름 = "이전", 자 = "만성", Name = "Li Dian")
const 李勝 = (名 = "李勝", 字 = "公昭", 이름 = "이승", 자 = "공소", Name = "Li Sheng")
const 李嚴 = (名 = "李嚴", 이름 = "이엄", Name = "Li Yan")
const 李堪 = (名 = "李堪", 이름 = "이감", Name = "Li Kan")
const 李孚 = (名 = "李孚", 字 = "子憲", 이름 = "이부", 자 = "자헌", Name = "Li Fu")
const 李封 = (Name = "Li Feng", 名 = "李封", 이름 = "이봉")
const 李恢 = (名 = "李恢", 字 = "德昻", 이름 = "이회", 자 = "덕앙", Name = "Li Hui")
const 李異 = (名 = "李異", 이름 = "이이", Name = "Li Yi")
const 李福 = (名 = "李福", 字 = "孫德", 이름 = "이복", 자 = "손덕", Name = "Li Fu")
const 李肅 = (名 = "李肅", 이름 = "이숙", Name = "Li Su")
const 李豊 = (名 = "李豊", 이름 = "이풍")
const 李通 = (名 = "李通", 字 = "文達", 이름 = "이통", 자 = "문달", Name = "Li Tong")
const 杜夔 = (名 = "杜夔", 字 = "公良", 이름 = "두기", 자 = "공량", Name = "Du Kui")
const 杜恕 = (名 = "杜恕", 字 = "務伯", 이름 = "두서", 자 = "무백", Name = "Du Shu")
const 杜瓊 = (名 = "杜瓊", 字 = "伯瑜", 이름 = "두경", 자 = "백유", Name = "Du Qiong")
const 杜畿 = (名 = "杜畿", 字 = "伯侯", 이름 = "두기", 자 = "백후", Name = "Du Ji")
const 杜襲 = (名 = "杜襲", 字 = "子緖", 이름 = "두습", 자 = "자서", Name = "Du Xi")
const 杜預 = (名 = "杜預", 이름 = "두예", Name = "Du Yu")
const 桓範 = (名 = "桓範", 字 = "元則", 이름 = "환범", 자 = "원칙", Name = "Huan Fan")
const 桓階 = (名 = "桓階", 字 = "伯緖", 이름 = "환계", 자 = "백서", Name = "Huan Jie")
const 梁冀 = (Name = "Liang Ji", 名 = "梁冀", 이름 = "양기")
const 梁綱 = (名 = "梁綱", 이름 = "양강", Name = "Liang Gang")
const 梁緖 = (名 = "梁緖", 이름 = "양서")
const 梁習 = (名 = "梁習", 字 = "子虞", 이름 = "양습", 자 = "자우", Name = "Liang Xi")
const 梁興 = (名 = "梁興", 이름 = "양흥", Name = "Liang Xing")
const 楊任 = (名 = "楊任", 이름 = "양임", Name = "Yang Ren")
const 楊俊 = (名 = "楊俊", 字 = "季才", 이름 = "양준", 자 = "계재", Name = "Yang Jun")
const 楊儀 = (名 = "楊儀", 이름 = "양의", Name = "Yang Yi")
const 楊奉 = (名 = "楊奉", 이름 = "양봉", Name = "Yang Feng")
const 楊定 = (名 = "楊定", 字 = "整修", 이름 = "양정", 자 = "정수", Name = "Yang Ding")
const 楊弘 = (名 = "楊弘", 이름 = "양홍", Name = "Yang Hong")
const 楊彪 = (名 = "楊彪", 字 = "文先", 이름 = "양표", 자 = "문선", Name = "Yang Biao")
const 楊懷 = (名 = "楊懷", 이름 = "양회", Name = "Yang Huai")
const 楊昻 = (名 = "楊昻", 이름 = "양앙")
const 楊松 = (名 = "楊松", 이름 = "양송", Name = "Yang Song")
const 楊欣 = (名 = "楊欣", 이름 = "양흔", Name = "Yang Xin")
const 楊濟 = (名 = "楊濟", 字 = "文通", 이름 = "양제", 자 = "문통", Name = "Yang Ji")
const 楊白 = (名 = "楊白", 이름 = "양백", Name = "Yang Bai")
const 楊祚 = (名 = "楊祚", 이름 = "양조", Name = "Yang Zuo")
const 楊秋 = (名 = "楊秋", 이름 = "양추", Name = "Yang Qiu")
const 楊肇 = (名 = "楊肇", 이름 = "양조", Name = "Yang Zhao")
const 楊脩 = (名 = "楊脩", 이름 = "양수")
const 楊醜 = (名 = "楊醜", 이름 = "양추", Name = "Yang Chou")
const 楊鋒 = (名 = "楊鋒", 이름 = "양봉")
const 楊阜 = (名 = "楊阜", 字 = "義山", 이름 = "양부", 자 = "의산", Name = "Yang Fu")
const 樂就 = (名 = "樂就", 이름 = "악취", Name = "Yue Jiu")
const 樂綝 = (名 = "樂綝", 이름 = "악침", Name = "Yue Lin")
const 樂進 = (名 = "樂進", 字 = "文謙", 이름 = "악진", 자 = "문겸", Name = "Yue Jin")
const 樊建 = (名 = "樊建", 字 = "長元", 이름 = "번건", 자 = "장원", Name = "Fan Jian")
const 樊氏 = (名 = "樊氏", 이름 = "번씨", Name = "Lady Fan")
const 樊稠 = (名 = "樊稠", 이름 = "번조", Name = "Fan Chou")
const 樊能 = (名 = "樊能", 이름 = "번능", Name = "Fan Neng")
const 樓玄 = (名 = "樓玄", 字 = "承先", 이름 = "누현", 자 = "승선", Name = "Lou Xuan")
const 橋玄 = (名 = "橋玄", 字 = "公祖", 이름 = "교현", 자 = "공조", Name = "Qiao Xuan")
const 橋瑁 = (名 = "橋瑁", 字 = "元偉", 이름 = "교모", 자 = "원위", Name = "Qiao Mao")
const 橋蕤 = (名 = "橋蕤", 이름 = "교유", Name = "Qiao Rui")
const 步協 = (名 = "步協", 이름 = "보협", Name = "Bu Xie")
const 步闡 = (名 = "步闡", 字 = "仲思", 이름 = "보천", 자 = "중사", Name = "Bu Chan")
const 步騭 = (名 = "步騭", 이름 = "보즐", Name = "Bu Zhi")
const 武安國 = (名 = "武安國", 이름 = "무안국")
const 段煨 = (名 = "段煨", 字 = "忠明", 이름 = "단외", 자 = "충명", Name = "Duan Wei")
const 段熲 = (名 = "段熲", 이름 = "단경")
const 毌丘儉 = (名 = "毌丘儉", 字 = "仲恭", 이름 = "관구검", 자 = "중공", Name = "Guanqiu Jian")
const 毌丘甸 = (名 = "毌丘甸", 字 = "子邦", 이름 = "관구전", 자 = "자방", Name = "Guanqiu Dian")
const 毌丘秀 = (名 = "毌丘秀", 이름 = "관구수", Name = "Guanqiu Xiu")
const 毛玠 = (名 = "毛玠", 字 = "孝先", 이름 = "모개", 자 = "효선", Name = "Mao Jie")
const 沙摩柯 = (名 = "沙摩柯", 이름 = "사마가", Name = "Shamoke")
const 沮授 = (名 = "沮授", 이름 = "저수", Name = "Ju Shou")
const 沮鵠 = (名 = "沮鵠", 이름 = "저곡", Name = "Ju Hu")
const 法正 = (名 = "法正", 字 = "孝直", 이름 = "법정", 자 = "효직", Name = "Fa Zheng")
const 波才 = (名 = "波才", 이름 = "파재", Name = "Bo Cai")
const 淩操 = (名 = "淩操", 이름 = "능조")
const 淩統 = (名 = "淩統", 字 = "公績", 이름 = "능통", 자 = "공적", Name = "Ling Tong")
const 凌統 = 淩統
const 淳于瓊 = (名 = "淳于瓊", 字 = "仲簡", 이름 = "순우경", 자 = "중간", Name = "Chunyu Qiong")
const 温恢 = (名 = "温恢", 이름 = "온회")
const 溫恢 = (名 = "溫恢", 字 = "曼基", 이름 = "온회", 자 = "만기", Name = "Wen Hui")
const 滕胤 = (名 = "滕胤", 이름 = "등윤", Name = "Teng Yin")
const 滕脩 = (名 = "滕脩", 字 = "显先", 이름 = "등수", 자 = "현선")
const 滿偉 = (名 = "滿偉", 字 = "公衡", 이름 = "만위", 자 = "공형", Name = "Man Wei")
const 滿奮 = (名 = "滿奮", 字 = "武秋", 이름 = "만분", 자 = "무추", Name = "Man Fen")
const 滿寵 = (名 = "滿寵", 字 = "伯寧", 이름 = "만총", 자 = "백녕", Name = "Man Chong")
const 潘濬 = (名 = "潘濬", 字 = "承明", 이름 = "반준", 자 = "승명", Name = "Pan Jun")
const 潘璋 = (名 = "潘璋", 字 = "文珪", 이름 = "반장", 자 = "문규", Name = "Pan Zhang")
const 潘鳳 = (名 = "潘鳳", 이름 = "반봉")
const 濮陽興 = (名 = "濮陽興", 字 = "子元", 이름 = "복양흥", 자 = "자원", Name = "Puyang Xing")
const 焦彝 = (名 = "焦彝", 이름 = "초이")
const 焦觸 = (名 = "焦觸", 이름 = "초촉", Name = "Jiao Chu")
const 牛輔 = (名 = "牛輔", 이름 = "우보", Name = "Niu Fu")
const 牛金 = (Name = "Niu Jin", 名 = "牛金", 이름 = "우금")
const 牽弘 = (名 = "牽弘", 이름 = "견홍", Name = "Qian Hong")
const 牽招 = (名 = "牽招", 字 = "子經", 이름 = "견초", 자 = "자경", Name = "Qian Zhao")
const 獻帝 = (名 = "獻帝", 이름 = "헌제")
const 王伉 = (名 = "王伉", 이름 = "왕항", Name = "Wang Kang")
const 王允 = (名 = "王允", 字 = "子師", 이름 = "왕윤", 자 = "자사", Name = "Wang Yun")
const 王匡 = (名 = "王匡", 字 = "公節", 이름 = "왕광", 자 = "공절", Name = "Wang Kuang")
const 王叡 = (名 = "王叡", 字 = "通耀", 이름 = "왕예", 자 = "통요", Name = "Wang Rui")
const 王基 = (名 = "王基", 이름 = "왕기", Name = "Wang Ji")
const 王威 = (名 = "王威", 이름 = "왕위", Name = "Wang Wei")
const 王宏 = (名 = "王宏", 字 = "長文", 이름 = "왕굉", 자 = "장문", Name = "Wang Hong")
const 王平 = (名 = "王平", 이름 = "왕평", Name = "Wang Ping")
const 王忠 = (名 = "王忠", 이름 = "왕충", Name = "Wang Zhong")
const 王惇 = (名 = "王惇", 이름 = "왕돈", Name = "Wang Dun")
const 王戎 = (名 = "王戎", 字 = "濬沖", 이름 = "왕융", 자 = "준충", Name = "Wang Rong")
const 王昶 = (名 = "王昶", 字 = "文舒", 이름 = "왕창", 자 = "문서", Name = "Wang Chang")
const 王朗 = (名 = "王朗", 字 = "景興", 이름 = "왕랑", 자 = "경흥", Name = "Wang Lang")
const 王業 = (名 = "王業", 이름 = "왕업", Name = "Wang Ye")
const 王淩 = (名 = "王淩", 이름 = "왕릉")
const 王渾 = (名 = "王渾", 이름 = "왕혼", Name = "Wang Hun")
const 王濬 = (名 = "王濬", 字 = "士治", 이름 = "왕준", 자 = "사치", Name = "Wang Jun")
const 王甫 = (名 = "王甫", 字 = "國山", 이름 = "왕보", 자 = "국산", Name = "Wang Fu")
const 王異 = (名 = "王異", 이름 = "왕이", Name = "Wang Yi")
const 王祥 = (名 = "王祥", 이름 = "왕상", Name = "Wang Xiang")
const 王粲 = (名 = "王粲", 이름 = "왕찬", Name = "Wang Can")
const 王累 = (名 = "王累", 이름 = "왕루", Name = "Wang Lei")
const 王經 = (名 = "王經", 字 = "彦偉", 이름 = "왕경", 자 = "언위", Name = "Wang Jing")
const 王肅 = (名 = "王肅", 字 = "子雍", 이름 = "왕숙", 자 = "자옹", Name = "Wang Su")
const 王脩 = (名 = "王脩", 字 = "淑治", 이름 = "왕수", 자 = "숙치")
const 王門 = (名 = "王門", 이름 = "왕문", Name = "Wang Men")
const 王雄 = (名 = "王雄", 字 = "元伯", 이름 = "왕웅", 자 = "원백", Name = "Wang Xiong")
const 王雙 = (名 = "王雙", 이름 = "왕쌍", Name = "Wang Shuang")
const 王韜 = (名 = "王韜", 이름 = "왕도")
const 王頎 = (名 = "王頎", 이름 = "왕기", Name = "Wang Qi")
const 甄氏 = (名 = "甄氏", 이름 = "견씨", Name = "Lady Zhen")
const 甘寧 = (名 = "甘寧", 字 = "興覇", 이름 = "감녕", 자 = "흥패", Name = "Gan Ning")
const 甯隨 = (名 = "甯隨", 이름 = "영수")
const 田楷 = (名 = "田楷", 이름 = "전해", Name = "Tian Kai")
const 田疇 = (名 = "田疇", 字 = "子泰", 이름 = "전주", 자 = "자태", Name = "Tian Chou")
const 田續 = (名 = "田續", 이름 = "전속", Name = "Tian Xu")
const 田豊 = (名 = "田豊", 字 = "元皓", 이름 = "전풍", 자 = "원호", Name = "Tian Feng")
const 田豐 = 田豊
const 田豫 = (名 = "田豫", 字 = "國讓", 이름 = "전예", 자 = "국양", Name = "Tian Yu")
const 申儀 = (名 = "申儀", 이름 = "신의", Name = "Shen Yi")
const 申敞 = (名 = "申敞", 字 = "泰雍", 이름 = "신창", 자 = "태옹")
const 申耽 = (名 = "申耽", 字 = "義擧", 이름 = "신탐", 자 = "의거", Name = "Shen Dan")
const 留平 = (名 = "留平", 이름 = "유평", Name = "Liu Ping")
const 留略 = (名 = "留略", 이름 = "유략", Name = "Liu Lue")
const 留贊 = (名 = "留贊", 이름 = "유찬", Name = "Liu Zan")
const 皇甫嵩 = (名 = "皇甫嵩", 字 = "義眞", 이름 = "황보숭", 자 = "의진", Name = "Huangfu Song")
const 盛憲 = (名 = "盛憲", 字 = "孝章", 이름 = "성헌", 자 = "효장", Name = "Sheng Xian")
const 盛曼 = (名 = "盛曼", 이름 = "성만", Name = "Sheng Man")
const 盧植 = (名 = "盧植", 字 = "子幹", 이름 = "노식", 자 = "자간", Name = "Lu Zhi")
const 盧毓 = (名 = "盧毓", 字 = "子家", 이름 = "노육", 자 = "자가", Name = "Lu Yu")
const 眭元進 = (名 = "眭元進", 이름 = "휴원진", Name = "Sui Yuanjin")
const 眭固 = (名 = "眭固", 이름 = "휴고", Name = "Sui Gu")
const 石苞 = (名 = "石苞", 字 = "仲容", 이름 = "석포", 자 = "중용", Name = "Shi Bao")
const 祖茂 = (名 = "祖茂", 이름 = "조무", Name = "Zu Mao")
const 祝融 = (名 = "祝融", 이름 = "축융")
const 禰衡 = (名 = "禰衡", 字 = "正平", 이름 = "예형", 자 = "정평", Name = "Mi Heng")
const 种劭 = (名 = "种劭", 字 = "申甫", 이름 = "충소", 자 = "신보", Name = "Chong Shao")
const 秦宓 = (名 = "秦宓", 이름 = "진복", Name = "Qin Mi")
const 秦朗 = (名 = "秦朗", 字 = "元明", 이름 = "진랑", 자 = "원명", Name = "Qin Lang")
const 秦松 = (名 = "秦松", 字 = "文表", 이름 = "진송", 자 = "문표", Name = "Qin Song")
const 程昱 = (名 = "程昱", 이름 = "정욱", Name = "Cheng Yu")
const 程普 = (名 = "程普", 字 = "德謨", 이름 = "정보", 자 = "덕모", Name = "Cheng Pu")
const 程武 = (名 = "程武", 이름 = "정무", Name = "Cheng Wu")
const 程畿 = (名 = "程畿", 字 = "季然", 이름 = "정기", 자 = "계연", Name = "Cheng Ji")
const 程秉 = (名 = "程秉", 字 = "德樞", 이름 = "정병", 자 = "덕추", Name = "Cheng Bing")
const 程遠志 = (名 = "程遠志", 이름 = "정원지")
const 程銀 = (名 = "程銀", 이름 = "정은", Name = "Cheng Yin")
const 穆順 = (名 = "穆順", 이름 = "목순")
const 章誑 = (名 = "章誑", 이름 = "장광", Name = "Zhang Kuang")
const 笮融 = (名 = "笮融", 이름 = "착융", Name = "Ze Rong")
const 管亥 = (名 = "管亥", 이름 = "관해", Name = "Guan Hai")
const 管輅 = (名 = "管輅", 字 = "公明", 이름 = "관로", 자 = "공명", Name = "Guan Lu")
const 簡雍 = (名 = "簡雍", 字 = "憲和", 이름 = "간옹", 자 = "헌화", Name = "Jian Yong")
const 糜夫人 = (名 = "糜夫人", 이름 = "미씨")
const 糜芳 = (名 = "糜芳", 字 = "子方", 이름 = "미방", 자 = "자방", Name = "Mi Fang")
const 麋芳 = 糜芳
const 紀靈 = (名 = "紀靈", 이름 = "기령", Name = "Ji Ling")
const 綸直 = (名 = "綸直", 이름 = "윤직")
const 羅憲 = (名 = "羅憲", 字 = "英則", 이름 = "나헌", 자 = "영칙", Name = "Luo Xian")
const 羊琇 = (Name = "Yang Xiu", 名 = "羊琇", 이름 = "양수")
const 羊祜 = (名 = "羊祜", 字 = "叔子", 이름 = "양호", 자 = "숙자", Name = "Yang Hu")
const 耿武 = (名 = "耿武", 字 = "文威", 이름 = "경무", 자 = "문위", Name = "Geng Wu")
const 胡奮 = (名 = "胡奮", 字 = "玄威", 이름 = "호분", 자 = "현위", Name = "Hu Fen")
const 胡濟 = (名 = "胡濟", 이름 = "호제", Name = "Hu Ji")
const 胡烈 = (名 = "胡烈", 字 = "玄武", 이름 = "호열", 자 = "현무", Name = "Hu Lie")
const 胡班 = (名 = "胡班", 이름 = "호반")
const 胡質 = (名 = "胡質", 字 = "文德", 이름 = "호질", 자 = "문덕", Name = "Hu Zhi")
const 胡車兒 = (名 = "胡車兒", 이름 = "호거아")
const 胡軫 = (名 = "胡軫", 字 = "文才", 이름 = "호진", 자 = "문재", Name = "Hu Zhen")
const 胡遵 = (名 = "胡遵", 이름 = "호준", Name = "Hu Zun")
const 臧覇 = (名 = "臧覇", 字 = "宣高", 이름 = "장패", 자 = "선고")
const 舒邵 = (名 = "舒邵", 字 = "仲膺", 이름 = "서소", 자 = "중응", Name = "Shu Shao")
const 花鬘 = (名 = "花鬘", 이름 = "화만")
const 荀勖 = (名 = "荀勖", 이름 = "순욱", Name = "Xun Xu")
const 荀彧 = (名 = "荀彧", 이름 = "순욱", Name = "Xun Yu")
const 荀悅 = (名 = "荀悅", 字 = "仲豫", 이름 = "순열", 자 = "중예")
const 荀愷 = (名 = "荀愷", 字 = "茂伯", 이름 = "순개", 자 = "무백", Name = "Xun Kai")
const 荀攸 = (名 = "荀攸", 字 = "公達", 이름 = "순유", 자 = "공달", Name = "Xun You")
const 荀爽 = (名 = "荀爽", 字 = "慈明", 이름 = "순상", 자 = "자명", Name = "Xun Shuang")
const 荀衍 = (名 = "荀衍", 字 = "休若", 이름 = "순연", 자 = "휴약", Name = "Xun Yan")
const 荀諶 = (名 = "荀諶", 字 = "友若", 이름 = "순심", 자 = "우약", Name = "Xun Chen")
const 荀顗 = (名 = "荀顗", 字 = "景倩", 이름 = "순의", 자 = "경천", Name = "Xun Yi")
const 華佗 = (名 = "華佗", 이름 = "화타", Name = "Hua Tuo")
const 華歆 = (名 = "華歆", 字 = "子魚", 이름 = "화흠", 자 = "자어", Name = "Hua Xin")
const 華覈 = (名 = "華覈", 이름 = "화핵", Name = "Hua He")
const 華雄 = (名 = "華雄", 이름 = "화웅", Name = "Hua Xiong")
const 萬彧 = (名 = "萬彧", 이름 = "만욱", Name = "Wan Yu")
const 董允 = (名 = "董允", 字 = "休昭", 이름 = "동윤", 자 = "휴소", Name = "Dong Yun")
const 董卓 = (名 = "董卓", 이름 = "동탁", Name = "Dong Zhuo")
const 董厥 = (名 = "董厥", 字 = "龔襲", 이름 = "동궐", 자 = "공습", Name = "Dong Jue")
const 董和 = (名 = "董和", 이름 = "동화", Name = "Dong He")
const 董扶 = (名 = "董扶", 字 = "茂安", 이름 = "동부", 자 = "무안", Name = "Dong Fu")
const 董承 = (名 = "董承", 이름 = "동승", Name = "Dong Cheng")
const 董旻 = (名 = "董旻", 이름 = "동민", Name = "Dong Min")
const 董昭 = (名 = "董昭", 字 = "公仁", 이름 = "동소", 자 = "공인", Name = "Dong Zhao")
const 董朝 = (名 = "董朝", 이름 = "동조", Name = "Dong Chao")
const 董荼那 = (名 = "董荼那", 이름 = "동도나")
const 董襲 = (名 = "董襲", 字 = "元代", 이름 = "동습", 자 = "원대", Name = "Dong Xi")
const 蒯良 = (名 = "蒯良", 字 = "子柔", 이름 = "괴량", 자 = "자유", Name = "Kuai Liang")
const 蒯越 = (名 = "蒯越", 字 = "異度", 이름 = "괴월", 자 = "이도", Name = "Kuai Yue")
const 蔡中 = (名 = "蔡中", 이름 = "채중", Name = "Cai Zhong")
const 蔡和 = (名 = "蔡和", 이름 = "채화", Name = "Cai He")
const 蔡氏 = (名 = "蔡氏", 이름 = "채씨", Name = "Lady Cai")
const 蔡琰 = (名 = "蔡琰", 이름 = "채염", Name = "Cai Yan")
const 蔡瑁 = (名 = "蔡瑁", 字 = "德珪", 이름 = "채모", 자 = "덕규", Name = "Cai Mao")
const 蔡瓚 = (名 = "蔡瓚", 字 = "茂珪", 이름 = "채찬", 자 = "무규")
const 蔡邕 = (名 = "蔡邕", 字 = "伯喈", 이름 = "채옹", 자 = "백개", Name = "Cai Yong")
const 蔣幹 = (名 = "蔣幹", 字 = "子翼", 이름 = "장간", 자 = "자익", Name = "Jiang Gan")
const 蔣斌 = (名 = "蔣斌", 이름 = "장빈", Name = "Jiang Bin")
const 蔣欽 = (名 = "蔣欽", 字 = "公奕", 이름 = "장흠", 자 = "공혁", Name = "Jiang Qin")
const 蔣濟 = (名 = "蔣濟", 이름 = "장제", Name = "Jiang Ji")
const 蔣班 = (名 = "蔣班", 이름 = "장반", Name = "Jiang Ban")
const 蔣琬 = (名 = "蔣琬", 字 = "公琰", 이름 = "장완", 자 = "공염", Name = "Jiang Wan")
const 蔣義渠 = (名 = "蔣義渠", 이름 = "장의거")
const 蔣舒 = (名 = "蔣舒", 이름 = "장서", Name = "Jiang Shu")
const 薛珝 = (名 = "薛珝", 이름 = "설후", Name = "Xue Xu")
const 薛瑩 = (名 = "薛瑩", 이름 = "설영", Name = "Xue Ying")
const 薛綜 = (名 = "薛綜", 字 = "敬文", 이름 = "설종", 자 = "경문", Name = "Xue Zong")
const 蘇由 = (名 = "蘇由", 이름 = "소유", Name = "Su You")
const 蘇飛 = (名 = "蘇飛", 이름 = "소비", Name = "Su Fei")
const 虞汜 = (名 = "虞汜", 字 = "世洪", 이름 = "우사", 자 = "세홍", Name = "Yu Si")
const 虞翻 = (名 = "虞翻", 字 = "仲翔", 이름 = "우번", 자 = "중상", Name = "Yu Fan")
const 衛旌 = (名 = "衛旌", 字 = "子旗", 이름 = "위정", 자 = "자기", Name = "Wei Jing")
const 衛瓘 = (名 = "衛瓘", 字 = "伯玉", 이름 = "위관", 자 = "백옥", Name = "Wei Guan")
const 衛臻 = (名 = "衛臻", 字 = "公振", 이름 = "위진", 자 = "공진", Name = "Wei Zhen")
const 袁尙 = (名 = "袁尙", 字 = "顯甫", 이름 = "원상", 자 = "현보", Name = "Yuan Shang")
const 袁尚 = 袁尙
const 袁忠 = (名 = "袁忠", 字 = "正甫", 이름 = "원충", 자 = "정보", Name = "Yuan Zhong")
const 袁成 = (名 = "袁成", 字 = "文開", 이름 = "원성", 자 = "문개")
const 袁渙 = (名 = "袁渙", 字 = "曜卿", 이름 = "원환", 자 = "요경", Name = "Yuan Huan")
const 袁熙 = (名 = "袁熙", 이름 = "원희", Name = "Yuan Xi")
const 袁燿 = (名 = "袁燿", 이름 = "원요")
const 袁紹 = (名 = "袁紹", 字 = "本初", 이름 = "원소", 자 = "본초", Name = "Yuan Shao")
const 袁胤 = (名 = "袁胤", 이름 = "원윤", Name = "Yuan Yin")
const 袁術 = (名 = "袁術", 字 = "公路", 이름 = "원술", 자 = "공로", Name = "Yuan Shu")
const 袁譚 = (名 = "袁譚", 字 = "顯思", 이름 = "원담", 자 = "현사", Name = "Yuan Tan")
const 袁逢 = (名 = "袁逢", 字 = "周陽", 이름 = "원봉", 자 = "주양")
const 袁遺 = (名 = "袁遺", 字 = "伯業", 이름 = "원유", 자 = "백업", Name = "Yuan Yi")
const 袁隗 = (名 = "袁隗", 字 = "次陽", 이름 = "원외", 자 = "차양", Name = "Yuan Wei")
const 裴元紹 = (名 = "裴元紹", 이름 = "배원소")
const 裴潛 = (名 = "裴潛", 字 = "文行", 이름 = "배잠", 자 = "문행", Name = "Pei Qian")
const 裴秀 = (名 = "裴秀", 字 = "季彦", 이름 = "배수", 자 = "계언", Name = "Pei Xiu")
const 許儀 = (名 = "許儀", 이름 = "허의", Name = "Xu Yi")
const 許劭 = (名 = "許劭", 이름 = "허소", Name = "Xu Shao")
const 許慈 = (名 = "許慈", 字 = "仁篤", 이름 = "허자", 자 = "인독", Name = "Xu Ci")
const 許攸 = (名 = "許攸", 字 = "子遠", 이름 = "허유", 자 = "자원", Name = "Xu You")
const 許褚 = (名 = "許褚", 字 = "仲康", 이름 = "허저", 자 = "중강", Name = "Xu Zhu")
const 許貢 = (名 = "許貢", 이름 = "허공", Name = "Xu Gong")
const 許靖 = (名 = "許靖", 字 = "文休", 이름 = "허정", 자 = "문휴", Name = "Xu Jing")
const 諸葛亮 = (名 = "諸葛亮", 字 = "孔明", 이름 = "제갈량", 자 = "공명", Name = "Zhuge Liang")
const 諸葛喬 = (名 = "諸葛喬", 이름 = "제갈교", Name = "Zhuge Qiao")
const 諸葛均 = (名 = "諸葛均", 이름 = "제갈균", Name = "Zhuge Jun")
const 諸葛常 = (名 = "諸葛常", 이름 = "제갈상")
const 諸葛恪 = (名 = "諸葛恪", 字 = "元遜", 이름 = "제갈각", 자 = "원손", Name = "Zhuge Ke")
const 諸葛珪 = (名 = "諸葛珪", 字 = "君貢", 이름 = "제갈규", 자 = "군공", Name = "Zhuge Gui")
const 諸葛瑾 = (名 = "諸葛瑾", 字 = "子瑜", 이름 = "제갈근", 자 = "자유", Name = "Zhuge Jin")
const 諸葛瞻 = (名 = "諸葛瞻", 字 = "思遠", 이름 = "제갈첨", 자 = "사원", Name = "Zhuge Zhan")
const 諸葛緖 = (名 = "諸葛緖", 이름 = "제갈서")
const 諸葛融 = (名 = "諸葛融", 字 = "叔長", 이름 = "제갈융", 자 = "숙장", Name = "Zhuge Rong")
const 諸葛誕 = (名 = "諸葛誕", 字 = "公休", 이름 = "제갈탄", 자 = "공휴", Name = "Zhuge Dan")
const 諸葛靚 = (名 = "諸葛靚", 字 = "仲思", 이름 = "제갈정", 자 = "중사", Name = "Zhuge Jing")
const 謝承 = (名 = "謝承", 字 = "偉平", 이름 = "사승", 자 = "위평", Name = "Xie Cheng")
const 謝旌 = (名 = "謝旌", 이름 = "사정", Name = "Xie Jing")
const 譙周 = (名 = "譙周", 字 = "允南", 이름 = "초주", 자 = "윤남", Name = "Qiao Zhou")
const 譚雄 = (名 = "譚雄", 이름 = "담웅")
const 貂蟬 = (名 = "貂蟬", 이름 = "초선")
const 費曜 = (名 = "費曜", 이름 = "비요", Name = "Fei Yao")
const 費禕 = (名 = "費禕", 이름 = "비의", Name = "Fei Yi")
const 費觀 = (名 = "費觀", 字 = "賓伯", 이름 = "비관", 자 = "빈백", Name = "Fei Guan")
const 費詩 = (名 = "費詩", 字 = "公擧", 이름 = "비시", 자 = "공거", Name = "Fei Shi")
const 賀齊 = (名 = "賀齊", 字 = "公苗", 이름 = "하제", 자 = "공묘", Name = "He Qi")
const 賈充 = (名 = "賈充", 字 = "公閭", 이름 = "가충", 자 = "공려", Name = "Jia Chong")
const 賈範 = (名 = "賈範", 이름 = "가범", Name = "Jia Fan")
const 賈詡 = (名 = "賈詡", 字 = "文和", 이름 = "가후", 자 = "문화", Name = "Jia Xu")
const 賈逵 = (名 = "賈逵", 字 = "梁道", 이름 = "가규", 자 = "양도", Name = "Jia Kui")
const 趙岐 = (名 = "趙岐", 字 = "邠卿", 이름 = "조기", 자 = "빈경", Name = "Zhao Qi")
const 趙廣 = (名 = "趙廣", 이름 = "조광", Name = "Zhao Guang")
const 趙弘 = (名 = "趙弘", 이름 = "조홍", Name = "Zhao Hong")
const 趙戩 = (名 = "趙戩", 字 = "叔茂", 이름 = "조전", 자 = "숙무", Name = "Zhao Jian")
const 趙範 = (名 = "趙範", 이름 = "조범", Name = "Zhao Fan")
const 趙累 = (名 = "趙累", 이름 = "조루", Name = "Zhao Lei")
const 趙統 = (名 = "趙統", 이름 = "조통", Name = "Zhao Tong")
const 趙雲 = (名 = "趙雲", 字 = "子龍", 이름 = "조운", 자 = "자룡", Name = "Zhao Yun")
const 蹋頓 = (名 = "蹋頓", 이름 = "답돈", Name = "Tadun")
const 車胄 = (名 = "車胄", 이름 = "차주", Name = "Che Zhou")
const 辛憲英 = (名 = "辛憲英", 이름 = "신헌영", Name = "Xin Xianying")
const 辛毗 = (名 = "辛毗", 字 = "佐治", 이름 = "신비", 자 = "좌치", Name = "Xin Pi")
const 辛評 = (名 = "辛評", 字 = "仲治", 이름 = "신평", 자 = "중치", Name = "Xin Ping")
const 逢紀 = (名 = "逢紀", 字 = "元圖", 이름 = "봉기", 자 = "원도", Name = "Pang Ji")
const 邊讓 = (名 = "邊讓", 字 = "文禮", 이름 = "변양", 자 = "문례", Name = "Bian Rang")
const 邢道榮 = (名 = "邢道榮", 이름 = "형도영")
const 邯鄲淳 = (名 = "邯鄲淳", 字 = "子禮", 이름 = "한단순", 자 = "자례", Name = "Handan Chun")
const 邴原 = (名 = "邴原", 字 = "根桕", 이름 = "병원", 자 = "근구", Name = "Bing Yuan")
const 邵悌 = (名 = "邵悌", 이름 = "소제", Name = "Shao Ti")
const 郝昭 = (名 = "郝昭", 字 = "伯道", 이름 = "학소", 자 = "백도", Name = "Hao Zhao")
const 郝普 = (名 = "郝普", 字 = "子太", 이름 = "학보", 자 = "자태", Name = "Hao Pu")
const 郝萌 = (名 = "郝萌", 이름 = "학맹", Name = "Hao Meng")
const 郤正 = (名 = "郤正", 이름 = "극정", Name = "Xi Zheng")
const 郭嘉 = (名 = "郭嘉", 字 = "奉孝", 이름 = "곽가", 자 = "봉효", Name = "Guo Jia")
const 郭圖 = (名 = "郭圖", 字 = "公則", 이름 = "곽도", 자 = "공칙", Name = "Guo Tu")
const 郭奕 = (名 = "郭奕", 字 = "伯益", 이름 = "곽혁", 자 = "백익", Name = "Guo Yi")
const 郭援 = (名 = "郭援", 이름 = "곽원", Name = "Guo Yuan")
const 郭攸之 = (名 = "郭攸之", 字 = "演長", 이름 = "곽유지", 자 = "연장", Name = "Guo Youzhi")
const 郭汜 = (名 = "郭汜", 이름 = "곽사", Name = "Guo Si")
const 郭淮 = (名 = "郭淮", 字 = "伯濟", 이름 = "곽회", 자 = "백제", Name = "Guo Huai")
const 郭馬 = (名 = "郭馬", 이름 = "곽마", Name = "Guo Ma")
const 鄂煥 = (名 = "鄂煥", 이름 = "악환")
const 鄒丹 = (名 = "鄒丹", 이름 = "추단", Name = "Zou Dan")
const 鄒氏 = (名 = "鄒氏", 이름 = "추씨", Name = "Lady Zou")
const 鄒靖 = (名 = "鄒靖", 이름 = "추정", Name = "Zou Jing")
const 鄧忠 = (名 = "鄧忠", 이름 = "등충", Name = "Deng Zhong")
const 鄧艾 = (名 = "鄧艾", 字 = "士載", 이름 = "등애", 자 = "사재", Name = "Deng Ai")
const 鄧芝 = (名 = "鄧芝", 字 = "伯苗", 이름 = "등지", 자 = "백묘", Name = "Deng Zhi")
const 鄧茂 = (名 = "鄧茂", 이름 = "등무")
const 鄧賢 = (名 = "鄧賢", 이름 = "등현", Name = "Deng Xian")
const 鄧颺 = (名 = "鄧颺", 字 = "玄茂", 이름 = "등양", 자 = "현무", Name = "Deng Yang")
const 鄭沖 = (名 = "鄭沖", 字 = "文和", 이름 = "정충", 자 = "문화", Name = "Zheng Chong")
const 鄭泰 = (名 = "鄭泰", 字 = "公業", 이름 = "정태", 자 = "공업")
const 鄭渾 = (名 = "鄭渾", 字 = "文公", 이름 = "정혼", 자 = "문공", Name = "Zheng Hun")
const 鄭玄 = (名 = "鄭玄", 字 = "康成", 이름 = "정현", 자 = "강성", Name = "Zheng Xuan")
const 金尙 = (名 = "金尙", 字 = "元休", 이름 = "김상", 자 = "원휴")
const 金旋 = (名 = "金旋", 字 = "元機", 이름 = "김선", 자 = "원기", Name = "Jin Xuan")
const 金環三結 = (名 = "金環三結", 이름 = "금환삼결")
const 金禕 = (名 = "金禕", 字 = "德禕", 이름 = "김의", 자 = "덕의", Name = "Jin Yi")
const 金褘 = (名 = "金褘", 이름 = "금위")
const 鍾會 = (名 = "鍾會", 字 = "士季", 이름 = "종회", 자 = "사계", Name = "Zhong Hui")
const 鍾毓 = (名 = "鍾毓", 이름 = "종육", Name = "Zhong Yu")
const 鍾繇 = (名 = "鍾繇", 字 = "元常", 이름 = "종요", 자 = "원상", Name = "Zhong Yao")
const 鍾離牧 = (名 = "鍾離牧", 字 = "子幹", 이름 = "종리목", 자 = "자간", Name = "Zhongli Mu")
const 鍾進 = (名 = "鍾進", 이름 = "종진", Name = "Zhong Jin")
const 閻圃 = (名 = "閻圃", 이름 = "염포", Name = "Yan Pu")
const 閻宇 = (名 = "閻宇", 字 = "文平", 이름 = "염우", 자 = "문평", Name = "Yan Yu")
const 閻晏 = (名 = "閻晏", 이름 = "염안")
const 閻柔 = (名 = "閻柔", 이름 = "염유", Name = "Yan Rou")
const 閻行 = (名 = "閻行", 이름 = "염행", Name = "Yan Xing")
const 閻象 = (名 = "閻象", 이름 = "염상", Name = "Yan Xiang")
const 關平 = (名 = "關平", 이름 = "관평", Name = "Guan Ping")
const 關彛 = (名 = "關彛", 이름 = "관이")
const 關索 = (名 = "關索", 이름 = "관색", Name = "Guan Suo")
const 關統 = (名 = "關統", 이름 = "관통", Name = "Guan Tong")
const 關羽 = (名 = "關羽", 字 = "雲長", 이름 = "관우", 자 = "운장", Name = "Guan Yu")
const 關興 = (名 = "關興", 字 = "安國", 이름 = "관흥", 자 = "안국", Name = "Guan Xing")
const 關靖 = (名 = "關靖", 이름 = "관정", Name = "Guan Jing")
const 闞澤 = (名 = "闞澤", 字 = "德潤", 이름 = "감택", 자 = "덕윤", Name = "Kan Ze")
const 阮瑀 = (名 = "阮瑀", 字 = "元瑜", 이름 = "완우", 자 = "원유", Name = "Ruan Yu")
const 阿會喃 = (名 = "阿會喃", 이름 = "아회남")
const 陳到 = (名 = "陳到", 字 = "叔至", 이름 = "진도", 자 = "숙지", Name = "Chen Dao")
const 陳化 = (名 = "陳化", 字 = "元耀", 이름 = "진화", 자 = "원요", Name = "Chen Hua")
const 陳壽 = (名 = "陳壽", 字 = "承祚", 이름 = "진수", 자 = "승조", Name = "Chen Shou")
const 陳宮 = (名 = "陳宮", 字 = "公臺", 이름 = "진궁", 자 = "공대", Name = "Chen Gong")
const 陳式 = (名 = "陳式", 이름 = "진식", Name = "Chen Shi")
const 陳應 = (名 = "陳應", 이름 = "진응", Name = "Chen Ying")
const 陳橫 = (名 = "陳橫", 이름 = "진횡")
const 陳武 = (名 = "陳武", 字 = "子烈", 이름 = "진무", 자 = "자열", Name = "Chen Wu")
const 陳泰 = (名 = "陳泰", 字 = "玄伯", 이름 = "진태", 자 = "현백", Name = "Chen Tai")
const 陳珪 = (名 = "陳珪", 字 = "漢瑜", 이름 = "진규", 자 = "한유", Name = "Chen Gui")
const 陳琳 = (名 = "陳琳", 字 = "孔璋", 이름 = "진림", 자 = "공장", Name = "Chen Lin")
const 陳登 = (名 = "陳登", 字 = "元龍", 이름 = "진등", 자 = "원룡", Name = "Chen Deng")
const 陳矯 = (名 = "陳矯", 字 = "季弼", 이름 = "진교", 자 = "계필", Name = "Chen Jiao")
const 陳祗 = (名 = "陳祗", 字 = "奉宗", 이름 = "진지", 자 = "봉종", Name = "Chen Zhi")
const 陳紀 = (名 = "陳紀", 이름 = "진기", Name = "Chen Ji")
const 陳群 = (名 = "陳群", 字 = "長文", 이름 = "진군", 자 = "장문", Name = "Chen Qun")
const 陳蘭 = (名 = "陳蘭", 이름 = "진란", Name = "Chen Lan")
const 陳表 = (名 = "陳表", 字 = "文奧", 이름 = "진표", 자 = "문오", Name = "Chen Biao")
const 陳震 = (名 = "陳震", 字 = "孝起", 이름 = "진진", 자 = "효기", Name = "Chen Zhen")
const 陳騫 = (名 = "陳騫", 이름 = "진건", Name = "Chen Qian")
const 陶丘洪 = (名 = "陶丘洪", 字 = "子林", 이름 = "도구홍", 자 = "자림", Name = "Taoqiu Hong")
const 陶濬 = (名 = "陶濬", 이름 = "도준")
const 陶璜 = (名 = "陶璜", 字 = "世英", 이름 = "도황", 자 = "세영", Name = "Tao Huang")
const 陶謙 = (名 = "陶謙", 字 = "恭祖", 이름 = "도겸", 자 = "공조", Name = "Tao Qian")
const 陸凱 = (名 = "陸凱", 字 = "敬風", 이름 = "육개", 자 = "경풍", Name = "Lu Kai")
const 陸康 = (名 = "陸康", 字 = "季寧", 이름 = "육강", 자 = "계녕", Name = "Lu Kang")
const 陸抗 = (名 = "陸抗", 字 = "幼節", 이름 = "육항", 자 = "유절", Name = "Lu Kang")
const 陸景 = (名 = "陸景", 字 = "士仁", 이름 = "육경", 자 = "사인", Name = "Lu Jing")
const 陸機 = (名 = "陸機", 字 = "士衡", 이름 = "육기", 자 = "사형", Name = "Lu Ji")
const 陸瑁 = (名 = "陸瑁", 字 = "子璋", 이름 = "육모", 자 = "자장", Name = "Lu Mao")
const 陸績 = (名 = "陸績", 字 = "公紀", 이름 = "육적", 자 = "공기", Name = "Lu Ji")
const 陸遜 = (名 = "陸遜", 字 = "伯言", 이름 = "육손", 자 = "백언", Name = "Lu Xun")
const 陸雲 = (名 = "陸雲", 字 = "士龍", 이름 = "육운", 자 = "사룡", Name = "Lu Yun")
const 雍闓 = (名 = "雍闓", 이름 = "옹개", Name = "Yong Kai")
const 雷薄 = (名 = "雷薄", 이름 = "뇌박", Name = "Lei Bo")
const 雷銅 = (名 = "雷銅", 이름 = "뇌동", Name = "Lei Tong")
const 霍峻 = (名 = "霍峻", 字 = "仲邈", 이름 = "곽준", 자 = "중막", Name = "Huo Jun")
const 霍弋 = (名 = "霍弋", 이름 = "곽익", Name = "Huo Yi")
const 鞏志 = (名 = "鞏志", 이름 = "공지", Name = "Gong Zhi")
const 韋康 = (名 = "韋康", 字 = "元將", 이름 = "위강", 자 = "원장", Name = "Wei Kang")
const 韋昭 = (名 = "韋昭", 이름 = "위소")
const 韓嵩 = (名 = "韓嵩", 이름 = "한숭", Name = "Han Song")
const 韓德 = (名 = "韓德", 이름 = "한덕")
const 韓忠 = (名 = "韓忠", 이름 = "한충", Name = "Han Zhong")
const 韓暹 = (名 = "韓暹", 이름 = "한섬", Name = "Han Xian")
const 韓浩 = (名 = "韓浩", 字 = "元嗣", 이름 = "한호", 자 = "원사", Name = "Han Hao")
const 韓玄 = (名 = "韓玄", 이름 = "한현", Name = "Han Xuan")
const 韓珩 = (名 = "韓珩", 字 = "子佩", 이름 = "한형", 자 = "자패", Name = "Han Heng")
const 韓當 = (名 = "韓當", 字 = "義公", 이름 = "한당", 자 = "의공", Name = "Han Dang")
const 韓胤 = (名 = "韓胤", 이름 = "한윤", Name = "Han Yin")
const 韓莒子 = (名 = "韓莒子", 이름 = "한거자", Name = "Han Juzi")
const 韓遂 = (名 = "韓遂", 이름 = "한수", Name = "Han Sui")
const 韓馥 = (名 = "韓馥", 이름 = "한복", Name = "Han Fu")
const 顏良 = (Name = "Yan Liang", 名 = "顏良", 이름 = "안량")
const 顔良 = 顏良
const 顧譚 = (名 = "顧譚", 字 = "子默", 이름 = "고담", 자 = "자묵", Name = "Gu Tan")
const 顧邵 = (名 = "顧邵", 字 = "孝則", 이름 = "고소", 자 = "효칙", Name = "Gu Shao")
const 顧雍 = (名 = "顧雍", 字 = "元歎", 이름 = "고옹", 자 = "원탄", Name = "Gu Yong")
const 馬休 = (名 = "馬休", 이름 = "마휴", Name = "Ma Xiu")
const 馬岱 = (名 = "馬岱", 이름 = "마대", Name = "Ma Dai")
const 馬延 = (名 = "馬延", 이름 = "마연", Name = "Ma Yan")
const 馬忠 = (名 = "馬忠", 이름 = "마충", Name = "Ma Zhong")
const 馬援 = (名 = "馬援", 字 = "文淵", 이름 = "마원", 자 = "문연")
const 馬玩 = (名 = "馬玩", 이름 = "마완", Name = "Ma Wan")
const 馬良 = (名 = "馬良", 字 = "季常", 이름 = "마량", 자 = "계상", Name = "Ma Liang")
const 馬謖 = (名 = "馬謖", 字 = "幼常", 이름 = "마속", 자 = "유상", Name = "Ma Su")
const 馬超 = (名 = "馬超", 字 = "孟起", 이름 = "마초", 자 = "맹기", Name = "Ma Chao")
const 馬遵 = (名 = "馬遵", 이름 = "마준", Name = "Ma Zun")
const 馬邈 = (名 = "馬邈", 이름 = "마막", Name = "Ma Miao")
const 馬鈞 = (名 = "馬鈞", 이름 = "마균", Name = "Ma Jun")
const 馬鐵 = (名 = "馬鐵", 이름 = "마철", Name = "Ma Tie")
const 馬雲騄 = (名 = "馬雲騄", 이름 = "마운록")
const 馬騰 = (名 = "馬騰", 字 = "壽成", 이름 = "마등", 자 = "수성", Name = "Ma Teng")
const 馮習 = (名 = "馮習", 字 = "休元", 이름 = "풍습", 자 = "휴원", Name = "Feng Xi")
const 駱統 = (名 = "駱統", 字 = "公緖", 이름 = "낙통", 자 = "공서", Name = "Luo Tong")
const 高堂隆 = (名 = "高堂隆", 이름 = "고당륭", Name = "Gaotang Long")
const 高定 = (名 = "高定", 이름 = "고정", Name = "Gao Ding")
const 高幹 = (名 = "高幹", 字 = "元才", 이름 = "고간", 자 = "원재", Name = "Gao Gan")
const 高昇 = (名 = "高昇", 이름 = "고승")
const 高柔 = (名 = "高柔", 字 = "文惠", 이름 = "고유", 자 = "문혜", Name = "Gao Rou")
const 高沛 = (名 = "高沛", 이름 = "고패", Name = "Gao Pei")
const 高翔 = (名 = "高翔", 이름 = "고상", Name = "Gao Xiang")
const 高覽 = (名 = "高覽", 이름 = "고람", Name = "Gao Lan")
const 高順 = (名 = "高順", 이름 = "고순", Name = "Gao Shun")
const 魏延 = (名 = "魏延", 이름 = "위연", Name = "Wei Yan")
const 魏攸 = (名 = "魏攸", 이름 = "위유", Name = "Wei You")
const 魏續 = (名 = "魏續", 이름 = "위속", Name = "Wei Xu")
const 魏諷 = (名 = "魏諷", 字 = "子京", 이름 = "위풍", 자 = "자경", Name = "Wei Feng")
const 魏邈 = (名 = "魏邈", 이름 = "위막", Name = "Wei Miao")
const 魯淑 = (名 = "魯淑", 이름 = "노숙", Name = "Lu Shu")
const 魯肅 = (名 = "魯肅", 이름 = "노숙", Name = "Lu Su")
const 魯芝 = (名 = "魯芝", 字 = "世英", 이름 = "노지", 자 = "세영", Name = "Lu Zhi")
const 鮑三娘 = (名 = "鮑三娘", 이름 = "포삼랑")
const 鮑信 = (名 = "鮑信", 이름 = "포신", Name = "Bao Xin")
const 鮑勛 = (名 = "鮑勛", 字 = "叔業", 이름 = "포훈", 자 = "숙업", Name = "Bao Xun")
const 鮑隆 = (名 = "鮑隆", 이름 = "포륭", Name = "Bao Long")
const 麋竺 = (名 = "麋竺", 字 = "子仲", 이름 = "미축", 자 = "자중", Name = "Mi Zhu")
const 麴義 = (名 = "麴義", 이름 = "국의", Name = "Qu Yi")
const 黃崇 = (名 = "黃崇", 이름 = "황숭", Name = "Huang Chong")
const 黃忠 = (名 = "黃忠", 字 = "漢升", 이름 = "황충", 자 = "한승", Name = "Huang Zhong")
const 黃承彦 = (名 = "黃承彦", 이름 = "황승언")
const 黃月英 = (名 = "黃月英", 이름 = "황월영")
const 黃權 = (名 = "黃權", 字 = "公衡", 이름 = "황권", 자 = "공형", Name = "Huang Quan")
const 黃皓 = (名 = "黃皓", 이름 = "황호")
const 黃祖 = (名 = "黃祖", 이름 = "황조", Name = "Huang Zu")
const 黃蓋 = (名 = "黃蓋", 字 = "公覆", 이름 = "황개", 자 = "공복", Name = "Huang Gai")
const 黨均 = (名 = "黨均", 이름 = "당균")
const 龐宏 = (名 = "龐宏", 字 = "巨師", 이름 = "방굉", 자 = "거사", Name = "Pang Hong")
const 龐德 = (名 = "龐德", 字 = "令明", 이름 = "방덕", 자 = "영명", Name = "Pang De")
const 龐會 = (名 = "龐會", 이름 = "방회", Name = "Pang Hui")
const 龐統 = (名 = "龐統", 字 = "士元", 이름 = "방통", 자 = "사원", Name = "Pang Tong")
const 龐羲 = (名 = "龐羲", 이름 = "방희", Name = "Pang Xi")
const 龔都 = (名 = "龔都", 이름 = "공도", Name = "Gong Du")
const 靈帝 = (名 = "靈帝", 이름 = "영제")

include("登場人物.jl")

end # module ThreeKingdoms.人名錄
